### PR TITLE
check for no unmaintained packages

### PR DESCRIPTION
**Pull request by Gkrumbach07**
## Related Issues and Dependencies

n/a
## This introduces a breaking change

- [ ] Yes
- [X] No

## This Pull Request implements

https://thoth-station.ninja/search/advise/adviser-221110165230-5736396adb425e9f/summary gives an error
## Description

its failing because of an issue in the the timeline view card. it is expecting a param that isnt there. added check for param to be there

### CODE REVIEW

**Comment by Gkrumbach07** [comment]
@harshad16 ready for review

**Review by harshad16 — APPROVED** [review]
/lgtm
thanks :100:

**Pull request merged**
