### PR TITLE
Package routing

### PR DESCRIPTION
**Pull request by Gkrumbach07**
## Related Issues and Dependencies
https://github.com/thoth-station/thoth-search/issues/34
https://github.com/thoth-station/thoth-search/issues/33
…

## This introduces a breaking change

- [X] No

## This Pull Request implements

It removes the use pypi metadata as a source. It adds a more precise way to access metadata. It uses the new `python/package/version/metadata`.  fixes bugs related to the migration to the new metadata.

### CODE REVIEW

**Comment by Gkrumbach07** [comment]
/hold

waiting on new user api endpoints to be pushed into production.
https://github.com/thoth-station/user-api/issues/1540
https://github.com/thoth-station/user-api/issues/1539

**Review by harshad16 — COMMENTED** [review]
lgtm :+1:

**Comment by goern** [comment]
can we get this feature in https://github.com/thoth-station/thoth-application/issues/2238 ?

**Pull request merged**
